#!/bin/bash
# Sync OpenAPI spec from Mantle backend to iOS APITypes package
#
# Usage: ./Scripts/sync-openapi.sh
#
# Copies the OpenAPI specification generated by `mantle generate openapi` in
# mantle-OfflineMediaDownloader to the iOS APITypes package. swift-openapi-generator
# runs as a build plugin and regenerates Swift types from the synced spec.
#
# Prerequisite: run `pnpm run generate:openapi` in mantle-OfflineMediaDownloader/
# to produce docs/api/openapi.yaml before running this sync.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IOS_ROOT="$(dirname "$SCRIPT_DIR")"
BACKEND_SPEC="$IOS_ROOT/../mantle-OfflineMediaDownloader/docs/api/openapi.yaml"
IOS_SPEC="$IOS_ROOT/APITypes/Sources/APITypes/openapi.yaml"

if [ ! -f "$BACKEND_SPEC" ]; then
    echo "Error: Backend OpenAPI spec not found at $BACKEND_SPEC"
    echo ""
    echo "To generate it, run in mantle-OfflineMediaDownloader/:"
    echo "  pnpm run generate:openapi"
    exit 1
fi

cp "$BACKEND_SPEC" "$IOS_SPEC"
echo "OpenAPI spec synced from Mantle backend to iOS"
echo "  Source: $BACKEND_SPEC"
echo "  Target: $IOS_SPEC"
